apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meetx-ai-services
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/meetx-ai-services:latest
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "4100"
            - name: CORS_ORIGIN
              value: ""
            - name: LOG_LEVEL
              value: "info"
